/**
 * Seed farmer profiles used when Supabase is not configured.
 * These can be seeded into the database via:
 *   supabase.from("farmer_profiles").insert(SEED_FARMERS)
 */

import type { FarmerProfile } from "./types";

export const SEED_FARMERS: FarmerProfile[] = [
  {
    id: "f-001",
    name: "Adeola Okonkwo",
    handle: "adeola.farm",
    farm_name: "Ogun Highlands Cooperative",
    location: "Ogun, NG",
    region: "West Africa",
    bio: "Third-generation maize farmer running a 120-hectare cooperative. ROOTCHAIN member since 2025. Every harvest is geotagged and milestone-verified on Stellar.",
    stellar_address: "GBFGCQEDMSB2XKFZE5FBZQ5H7JRU6BPXQJZ67PGJHG3RVKF4LXX4GS",
    verified: true,
    total_harvests: 8,
    total_funded: 284000,
    active_listings: 2,
    specialties: ["Premium Maize", "Organic Sorghum"],
    join_year: 2025,
    avatar_color: "#84CC16",
    verification_tier: "trusted_operator",
    harvest_success_rate: 94.6,
    location_verified: true,
    reputation_score: 91,
    seasons_active: 14,
    created_at: "2025-03-15T09:00:00Z",
  },
  {
    id: "f-002",
    name: "Kwame Adjei",
    handle: "kwame.cocoa",
    farm_name: "Ashanti Cocoa Collective",
    location: "Kumasi, GH",
    region: "West Africa",
    bio: "Leading cocoa cooperative in the Ashanti region. Grade-A certified with IPFS-verified lab reports. 97% quality score across all harvests on the platform.",
    stellar_address: "GC3GJUKMXLMIMQNPLXBLHZMHM6MR2X2BJZD2NHQSHJ7GZN3PJKFTWY3",
    verified: true,
    total_harvests: 12,
    total_funded: 620000,
    active_listings: 1,
    specialties: ["Grade-A Cocoa", "Specialty Coffee"],
    join_year: 2025,
    avatar_color: "#A16207",
    verification_tier: "export_certified",
    harvest_success_rate: 97,
    location_verified: true,
    reputation_score: 94,
    seasons_active: 18,
    created_at: "2025-02-20T10:00:00Z",
  },
  {
    id: "f-003",
    name: "Ibrahim Lawal",
    handle: "ibrahim.ranch",
    farm_name: "Plateau Ranches",
    location: "Jos, NG",
    region: "West Africa",
    bio: "Fourth-generation cattle rancher operating across 400 hectares on the Jos Plateau. Milestone-based payouts tied to herd weight benchmarks verified by certified vets.",
    stellar_address: "GDKC4FNH4GRG3AJQPAJIQFVQXRQNQD2RZMNJDTQKZ4EPIPPMZPXYNFD",
    verified: true,
    total_harvests: 5,
    total_funded: 480000,
    active_listings: 1,
    specialties: ["Red Angus Cattle", "Free-Range Poultry"],
    join_year: 2025,
    avatar_color: "#DC2626",
    verification_tier: "veterinary_attested",
    harvest_success_rate: 88,
    location_verified: true,
    reputation_score: 86,
    seasons_active: 11,
    created_at: "2025-01-10T07:00:00Z",
  },
  {
    id: "f-004",
    name: "Ifeoma Bassey",
    handle: "ifeoma.aqua",
    farm_name: "Lekki Aquaculture",
    location: "Lagos, NG",
    region: "West Africa",
    bio: "Aquaculture pioneer running the largest indoor tilapia operation in Lagos State. Precision-controlled water quality with IoT sensors posting live data to IPFS.",
    stellar_address: null,
    verified: true,
    total_harvests: 9,
    total_funded: 195000,
    active_listings: 2,
    specialties: ["Tilapia", "Catfish", "Shrimp"],
    join_year: 2025,
    avatar_color: "#38BDF8",
    verification_tier: "aquatech_labs",
    harvest_success_rate: 90,
    location_verified: true,
    reputation_score: 88,
    seasons_active: 9,
    created_at: "2025-04-01T08:00:00Z",
  },
  {
    id: "f-005",
    name: "Nneka Eze",
    handle: "nneka.roots",
    farm_name: "Cross River Roots",
    location: "Calabar, NG",
    region: "West Africa",
    bio: "Processing and export specialist for cassava and yam. Runs a value-chain model connecting 40 smallholder farmers to the platform's investor pool.",
    stellar_address: null,
    verified: true,
    total_harvests: 6,
    total_funded: 142000,
    active_listings: 1,
    specialties: ["White Cassava", "Yam", "Sweet Potato"],
    join_year: 2025,
    avatar_color: "#EAB308",
    verification_tier: "value_chain_partner",
    harvest_success_rate: 85,
    location_verified: true,
    reputation_score: 82,
    seasons_active: 7,
    created_at: "2025-05-12T11:00:00Z",
  },
  {
    id: "f-006",
    name: "Amara Kone",
    handle: "amara.sorghum",
    farm_name: "Bamako Drylands",
    location: "Bamako, ML",
    region: "West Africa",
    bio: "Climate-resilient dryland farming using advanced deficit-irrigation. Specialises in drought-resistant sorghum varieties for both food and industrial markets.",
    stellar_address: null,
    verified: false,
    total_harvests: 3,
    total_funded: 38000,
    active_listings: 1,
    specialties: ["Sorghum", "Millet", "Cowpea"],
    join_year: 2026,
    avatar_color: "#F97316",
    verification_tier: "trial",
    harvest_success_rate: 72,
    location_verified: false,
    reputation_score: 58,
    seasons_active: 3,
    created_at: "2026-01-05T09:00:00Z",
  },
];
